Create: Landing Page and Navbar
gdsc-nits-org/oikyotaan-2023 pull request #1
Opened 2023-03-23 20:30 UTC by Dimpal-Kalita

2023-03-23 21:14 UTC, codadept requested changes

2023-03-23 21:14 UTC, codadept commented on src/Components/Landing/Images/Background.png
Create a public directory in the root along-side src. And also create an `assets` directory inside public.

Move these images from `src/Components/Landing/Images` to `public/assets/` and then you can access the images in your HTML as

Suppose you want to use the image in the location `public/assets/background.png`, then 

```html
<img src="/assets/background.png" alt="background"/>
```

Do these for all the images in `src/Components/Landing/Images`

> Note: No need to write `public` as vite serves public as root `/`

2023-03-23 21:14 UTC, codadept commented on src/Components/Landing/Landing.jsx
> +import React from "react";
No need to import React since release of `React 17`

2023-03-23 21:14 UTC, codadept commented on src/Components/Landing/landing.module.scss
Don't use any absolute units like `px, pt, cm` etc. Only use relative units like `vh, vw, rem, %` etc.

2023-03-23 21:14 UTC, codadept commented on src/Components/Landing/Landing.jsx
> +        <img src={birdRight} alt="" />
Provide appropriate alt text to all the images.

2023-03-23 21:14 UTC, codadept commented on src/Components/Navbar/Navbar.jsx
> +        <Link to="/Artists">
Lower case all the links `/artists`, `/sponsor`, `/team`, `/gallery`

2023-03-23 21:14 UTC, codadept commented on src/Pages/Home/Home.jsx
> +import Landing from "../../Components/Landing/Landing";
Follow the template properly. Import and export the component in `src/Components/index.jsx` as 

```jsx
import Button from "./Button/Button";
import Landing from "./Landing/Landing";

export {Button, Landing};
```

and then you can use it here as 

```jsx

import { Landing } from "../../Components";
```

2023-03-23 21:14 UTC, codadept commented on src/Components/Navbar/Navbar.jsx
Use the Navbar in App.jsx

2023-03-23 21:29 UTC, codadept commented
1) Eslint errors and warnings

![image](https://user-images.githubusercontent.com/63517465/227364606-b4b82279-c27d-4759-b1ea-161e492b1ace.png)

When you will run `pnpm lint` (which is also automatically set as recommit hook), you may get errors or warnings (like above). Your task is to fix those errors or warnings before pushing the code.

2) Positioning issues

![image](https://user-images.githubusercontent.com/63517465/227365027-ef501bbd-54af-4e7e-9dba-9696118e2bdc.png)

Basically don't use pixels or other absolute units as it would seem fine in your PC, but maybe broken in someone else's resolution. Also don't center stuffs using left right property. Fix this issue, as you can see the eyes are not in the center of the website in my device.

3) Also the background image is stretched

Instead of using `background-size` property, use these properties (understand why am I telling you to use this)

![image](https://user-images.githubusercontent.com/63517465/227366001-f28570f6-d4b3-4416-9173-b705c0543330.png)

Also once you have shifted the images to `public/assets/background.png` then new url would be `background-image : url("/assets/background.png")`

4) No need to compile the scss file

![image](https://user-images.githubusercontent.com/63517465/227366700-ac5b90e2-39c7-4b06-ad16-f2f30240e1cd.png)

No need to compile the scss files to css, map.css files. They are internally done by vite. So delete all the .css and .map.css files you have created. 

![image](https://user-images.githubusercontent.com/63517465/227366611-3129db20-b67d-4534-aec6-358184cf0dfa.png)

Also you need to import the `Landing.module.scss` file instead of the css file.

Also try to follow the convention of file names :) Checkout other .scss file names

If the component file name is `Landing.jsx` then it's scss file name would be `Landing.module.scss` with a capital `L`. Follow the conventions properly

2023-03-24 09:08 UTC, codadept requested changes

2023-03-24 09:08 UTC, codadept commented on src/Components/Navbar/Navbar.jsx
> +import React from "react";
Remove the React import. Its redundant

2023-03-28 07:46 UTC, username-naz approved these changes

2023-03-28 07:53 UTC, merged