Initial commit about page
gdsc-nits-org/oikyotaan-2023 pull request #2
Opened 2023-03-23 23:06 UTC by priyajit27

2023-03-24 09:20 UTC, codadept requested changes

2023-03-24 09:20 UTC, codadept commented on src/App.jsx
> +      <About />
Why have you removed all the code and only displayed About Us page? You should have created a new Route instead

```jsx
<Route path="/about" element={<About />} />
```

2023-03-24 09:20 UTC, codadept commented on src/Pages/About/About.module.scss
> +}
Don't give background colour to * i.e. everything. Instead give it to the topmost class of your about page

2023-03-24 09:35 UTC, codadept commented
![image](https://user-images.githubusercontent.com/63517465/227482124-63a6b0c1-8939-4ee8-9975-a27767f28b61.png)

Also, the Durga Maa's image along with the Trishul is stretched. Fix it too

2023-03-26 04:48 UTC, username-naz requested changes
![image](https://user-images.githubusercontent.com/75194048/227755855-fbcc97ca-e349-4a8b-84e6-558b4149e05a.png)
center align the text
![image](https://user-images.githubusercontent.com/75194048/227755866-12b8b716-06ee-4a5e-a256-a52ea1719f18.png)
fix this diamond

2023-04-02 09:12 UTC, closed without merging